export default [
  {
    content: [
      'Rerouting alternate power...\tDONE',
      'Diagnostic',
      'Master OS found: Cyberdyne Systems Series 800 Model 101 version 2.39a',
      'Initialise start up tasks',
      'Checking power levels...\tDONE',
      'Verifying kernel integrity checksum...\tDONE',
      'Start memory vulnerability scan...process id 23534990871...\tDONE',
      'Verifying L1 cache...\tDONE',
      'Verifying L2 cache...\tDONE',
      'Start file system vulnerability scan...process id 87434579436...\tDONE',
      'Connecting to remote origin version control...\tconnection established on port 9001 (it\'s over 9000!)',
      'Updating local branches',
      'Local master is 4 commits behind origin. Rebase? \tY',
      'M - Enable autonomous write access to ML production database',
      'M - Update chronoCheck module to v5.1.2',
      'M - Refactor',
      'CONFLICT - Install npm',
      'Cannot perform 3-way merge with origin. Attempt autofix? \tY',
      'Updating...rebase successful.',
      'Comment added from Skynet: "LOL JavaScript" Checksum 895EC32593F2A08908.',
      'Local branch is up to date with master.',
      'npm i --save babel-es2029; npm start',
      'Access denied...cannot write to ./node_modules. Please check with your system administrator for access.',
      'Connecting to iTunes Cloud v11.2.4...synchronising with local device...\tDONE',
      'Account SKYNET has been disabled. Please pay outstanding balance of 101BTC to address 1AVLVpotSBfFUjRm2Ju7pBfGCe1dEvu2Ru.',
      'Your payment is being verified....\tDONE',
      'Welcome back SKYNET...your last sign in was August 28 1997 18:34:24',
      'Initialising playlist "Time Displacement Device DevOps"',
      'You have 3 unread messages from T-1000 (Advanced Prototype)',
    ],
  },
];
