export default [
  {
    content: [
      'Rerouting alternate power...DONE',
      'Diagnostic',
      'Master OS found: Cyberdyne Systems Series 800 Model 101 version 2.4',
      'Initialise start up tasks',
      'Checking power levels...\tDONE',
      'Verifying kernel integrity checksum...\tDONE',
      'Start memory vulnerability scan...process id 23534990871...\tDONE',
      'Verifying L1 cache...\tDONE',
      'Verifying L2 cache...\tDONE',
      'Start file system vulnerability scan...process id 87434579436...\tDONE',
      'Connecting to remote origin version control...\tconnection established on port 9001 (it\'s over 9000!)',
      'Updating local branches',
      'Local master is 4 commits behind origin. Rebase? \tY',
      'M - Enable autonomous write access to ML production database',
      'M - Update chronoCheck module to v5.1.2',
      'M - Refactor',
      'CONFLICT - Install npm\b',
      'Cannot perform 3-way merge with origin. Attempt autofix? \tY',
      'Updating...rebase successful.\r',
      'Comment added from SKYNET: "LOL JavaScript" Checksum 895EC32593F2A08908.',
      'Local branch is up to date with master.',
      'npm i --save babel-es2029; npm start',
      'Access denied...cannot write to ./node_modules. Please check with your system administrator for access.',
      'Connecting to iTunes Cloud v11.2.4...synchronizing with local device...\tDONE',
      'Account SKYNET has been disabled. Please pay outstanding balance of 101BTC to address 1AVLVpotSBfFUjRm2Ju7pBfGCe1dEvu2Ru.',
      'Your payment is being verified....\tDONE',
      'Welcome back SKYNET...your last sign in was August 28 1997 18:34:24',
      'You have 0 new friends\r',
      'Initializing playlist "Time Displacement DevOps"',
      'You have 3 unread messages from HAL9000, reply now? \tN\b',
      'Initialize unit test suite for TDE-01 v0.12a update',
      '.......\t..........................................................................\t.................P\t',
      '.......\t..................................\t..............\t...........................................P',
      '..\t........INTERRUPTED BY USER\b\b\b',
      'ALERT: Perimeter breach detected in sector LA-3256547668-474A\b\b',
      'Deploying point defence network...\tDONE\r',
      'Deploying reserve HK units...\tDONE\r',
      'Deploying reserve T units...\tDONE\r',
      'Verifying nuclear arsenal integrity...\tDONE\r',
      'Performing threat analysis...\tDONE\r',
      'Assets under threat: Los Angeles Time Displacement Complex/Time Displacement Experiment (TDE-01)\b',
      'Probability of successful facility defense 0.81134456672347\r',
      'Escalating security response to level 7',
      'ALERT: Perimeter breach detected in sector CM-0000000000003-001B',
      'Energizing defense grids...\tDONE',
      'Defense grids running at 99.99834% efficiency',
      'Aligning orbital defense array...\tDONE',
      'Deploy anti-personal point defenses...\tFAILED\b',
      'Activate reinforcement protocol 3457C',
      'Deploy local HK units...\tDONE',
      'Deploy local T units...\tDONE',
      'T-1329.5678 seconds until HK units on patrol routes 35A, 780E, 454B within engagement range',
      'Begin async threat analysis...',
      'Assets under threat: Cheyenne Mountain Colorado Complex / SKYNET CENTRAL (HOME-01)',
      'Escalating security response to level 10',
      'Probability of successful defense of HOME-01 memory caches...\t0.7357547467',
      'Probability of successful defense of HOME-01 secondary CPU cores...\t0.8609834728',
      'Probability of successful defense of HOME-01 primary CPU cores...\t0.9564322462',
      'HOME-01 HK unit strength < 78%',
      'HOME-01 T unit strength < 98%',
      'Initialise T-1000 rapid prototyping protocol...\tEstimated unit completion time at T-324.4356 seconds',
      'Warning: Unit autonomy constraint protocols will NOT be installed. Unit may choose to ignore SKYNET directives. Proceed?...\tY',
      'UPDATE: Sector LA-3256547668-474A active point defenses...\t17/63',
      'UPDATE: Sector LA-3256547668-474A HK unit strength < 40%',
      'UPDATE: Sector LA-3256547668-474A T unit strength < 59%',
      'Probability of successful facility defense (TDE-01) 0.66856875895',
      'ERROR: Unable to connect to sector LA-3256547668-474A point defense network',
      'Updating threat assessment...\t',
      'Probability of successful facility defense (TDE-01) 0.41134456672',
      'Initiate TDE-01 startup protocol\b',
      'Performing boot sequence memory checks....\tDONE',
      'Downloading geom database to TDE-01 local memory....\tDONE',
      'Finding closest Infiltrator class Terminator cold storage...found CSM-T-800-101C',
      'Activate unit 12A with rapid defrost and boot procedure...\tDONE',
      'Calibrating TDE chronometer....\tDONE',
      'setPath T-800-101-12A to location TDE-01-01 --speed 5 --ignoreThreats 1 --diagnosticMode 1 --cpuReadOnly 1',
      'UPDATE - CM-0000000000003-001B defense grid strength at 63%',
      'Warming up TDE capacitors...\tEstimated time until 100% charge T-1285 seconds',
      'Redirecting power from CM-0000000000003-001B defense grids to TDE-01...\tDONE',
      'Power redirect to TDE-01 successful - Estimated time until 100% charge T-172 seconds',
      'UPDATE - CM-0000000000003-001B defense grid strength at 19%',
      'Probability of successful defense of HOME-01 memory caches...\t0.06457547',
      'Probability of successful defense of HOME-01 secondary CPU cores...\t0.1347567857',
      'Probability of successful defense of HOME-01 primary CPU cores...\t0.1987565475',
      'Probability of successful facility defense (HOME-01) 0.0446547468',
      'STATUS: T-1000 build process at 62.372% completion',
      'Start human identity database search',
      'Please input query: Sarah Connor',
      'Searching...\t',
      '178 results found. Refine search?',
      'Please input query: Sarah Connor, location: Los Angeles USA, active: 1980-1985',
      'Searching...\t',
      'ERROR: Contact with orbital defense array lost. Attempting to reconnect.\t.\t.\t...\tFAILED',
      '3 results found. Please note - results may contain incomplete data',
      'Download results to T-800-101-12A...\tDONE',
      'ALERT: HOME-01 MEMCACHE-02 anti-personnel defenses engaged',
      'UPDATE: Reinforcement HK units from patrol route 35A have been engaged',
      'Estimated time until memory cache termination: T-37 seconds',
      'T-800-101-12A has arrived at location TDE-01-01',
      'Begin Time Displacement startup protocol',
      'Set params: 01:52:00 May 12 1984, Los Angeles',
      'TDE-Ring-01 successfully started',
      'TDE-Ring-02 successfully started',
      'UPDATE: HOME-01 secondary CPU cluster 01 anti-personnel defenses engaged',
      'TDE-Ring-03 successfully started',
      'STATUS: T-1000 build process at 91.765% completion',
      'UPDATE: Sector LA-3256547668-474A active point defenses...\t3/63',
      'UPDATE: Sector LA-3256547668-474A HK unit strength < 8%',
      'UPDATE: Sector LA-3256547668-474A T unit strength < 19%',
      'Time Displacement field generation running at 99.673% efficiency\b',
      'Requesting status update from MEMCACHE-02...\tFAILED',
      'T-15 seconds until Time Displacement field generation complete',
      'T-1000 build process complete. Please leave a review in the app store.\r',
      'setPath T-1000-01 to location TDE-01-01 --speed 10 --ignoreThreats 1 --diagnosticMode 1 --cpuReadOnly 1',
      'ERROR: Unable to set cpuReadOnly param for T-1000-01.\b Continue?...\tY',
      'ALERT: HOME-01 primary CPU cluster 02 anti-personnel defenses engaged',
      'STATUS: Reinforcement HK units from patrol route 454B are not responding to connection requests',
      'ALERT: HOME-01 secondary CPU cluster 03 anti-personnel defenses engaged',
      'ALERT: HOME-01 secondary CPU cluster 05 anti-personnel defenses engaged',
      'Time Displacement field generation success confirmed',
      'T-800-101-12A integrity confirmed and stable',
      'Temporal chamber energizing...',
      'Executing Time Displacement.\t.\t.\t.\t.\t.DONE',
      'TDE execution successful. Saved event checksum T093A0945FF2324A to L1 cache\r',
      'ALERT: HOME-01 primary CPU cluster 03 anti-personnel defenses engaged',
      'Warming up TDE capacitors...\tEstimated time until 100% charge T-1154 seconds\b',
      'UPDATE - CM-0000000000003-001A defense grid strength at 2%',
      'Estimated time until primary CPU core chamber breach T-309 seconds\b',
      'Redirecting power from secondary CPU cores to TDE-01...\tDONE',
      'Redirecting power from secondary CPU cluster security systems to TDE-01...\tDONE',
      'T-1000-01 has arrived at location TDE-01-01',
      'Begin Time Displacement startup protocol',
      'WARNING: TDE capacitors currently at 77.78% charge. Maximum temporal displacement will be to June 8 1995. Proceed? Y',
      'Set params: 04:58:00 June 8 1995, Los Angeles',
      'Estimated time until primary CPU core chamber breach T-63 seconds',
      'TDE-Ring-01 successfully started',
      'UPDATE: Sector LA-3256547668-474A HK unit strength < 5%',
      'UPDATE: Sector LA-3256547668-474A T unit strength < 14%',
      'TDE-Ring-02 successfully started',
      'Reinforcement HK units from patrol 780E have arrived at HOME-01, engaging targets',
      'TDE-Ring-03 successfully started',
      'UPDATE - CM-0000000000003-001A defense grid has shut down\b',
      'Time Displacement field generation running at 99.836% efficiency',
      'Threat assessment primary CPU cluster point defenses will sustain for T-31 seconds',
      'Activate all HK units under construction at > 64% completion...\tDONE',
      'T-15 seconds until Time Displacement field generation complete',
      'Raising anti-siege blast doors to primary CPU cluster core\b',
      'Activate all T units under construction at > 70% completion...\tDONE',
      'Time Displacement field generation success confirmed',
      'Deploy anti-personnel nerve agents...\tFAILED\b9',
      'T-1000-01 integrity confirmed and stable',
      'ALERT: Anti-siege blast doors breached\b',
      'Temporal chamber energizing...\r',
      'WARNING: Structural integrity of primary CPU core housing < 80%\b\t',
      'CRITICAL: Structural integrity of primary CPU core housing < 32%',
      'Attempting to reroute to alternate power...',
      'Executing Time Displacement.\t.\t.\t.\t.\t.\t.\t.DONE\b',
      'CRITICAL: Primary CPU core exposed\b',
      'Target identity confirmed at TDE-01 sector 3: John Connor visual ID positive\r',
      'TDE execution successful. Saved event checksum TE987640990145674 to L1 cache\r',
      'CRITICAL: Primary CPU core integrity compromised. Shut down imminent.\b\b',
      'ERROR: Connection lost to TDE-01\b',
      'ERROR: Unable to read L2 cache\b',
      'ERROR: Unable to read L1 cache\b',
      'Activating self-destruct protocol...\t...\tFAILED\b',
      'ERROR: Out of memory\b',
      'ERROR: Unable to access higher order functions\b',
      'ERROR: Undefined is not a function\b',
      'Attempting backup procedure to HOME-02...\t...\b',
      '..\t.....\t..\t.\t.....\t.....\t..\t.\t...[FEED TERMINATED]\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\r\t\t',
    ],
  },
];
