export const RESET_APP = 'RESET_APP';

export const ARTICLES_FETCHED = 'ARTICLES_FETCHED';

export const LOG_STORY_FOCUSED = 'LOG_STORY_FOCUSED';
export const LOG_STORY_BLURRED = 'LOG_STORY_BLURRED';
